export type ServiceTier = {
  id: string;
  title: string;
  category: string;
  unit: string;
  tag?: 'POPULAR' | 'ENTERPRISE';
  ngn: string;
  ngnRaw: number;
  usd: string;
  usdRaw: number;
  priceSuffix?: string;
  description: string;
  delivery: string;
  support: string;
  features: string[];
  deliverables: string[];
};

export type PricingCategory = {
  id: string;
  label: string;
  rev: string;
  tiers: ServiceTier[];
};

export const categories: PricingCategory[] = [
  {
    id: 'static',
    label: 'Static & Landing',
    rev: 'REV 1.0',
    tiers: [
      {
        id: 'landing-page',
        title: 'Landing Page',
        category: 'static',
        unit: 'UNIT / S-01',
        ngn: '150,000',
        ngnRaw: 150000,
        usd: '100',
        usdRaw: 100,
        description: 'High-converting single-page architecture engineered for maximum lead capture and first-impression authority.',
        delivery: '5–7 DAYS',
        support: '30 DAYS',
        features: [
          'Strategic single-page design focused on conversion',
          'Mobile-first responsive architecture',
          'Basic SEO optimization with meta tags',
          'Lead capture form with email integration',
          'Google Analytics setup & event tracking',
          'Contact form with spam protection',
          'Social media link integration',
          'SSL certificate setup',
        ],
        deliverables: [
          'Fully functional landing page',
          'Source code and all assets',
          'Deployment assistance',
          'Basic documentation',
        ],
      },
      {
        id: 'personal-portfolio',
        title: 'Personal Portfolio',
        category: 'static',
        unit: 'UNIT / S-02',
        ngn: '250,000',
        ngnRaw: 250000,
        usd: '167',
        usdRaw: 167,
        description: 'A precision-crafted showcase that establishes your professional identity and separates you from the competition.',
        delivery: '7–10 DAYS',
        support: '45 DAYS',
        features: [
          'Up to 5 beautifully crafted pages',
          'Custom personal branding & visual identity',
          'Interactive portfolio gallery with lightbox',
          'Advanced SEO optimization',
          'Contact form with spam protection',
          'Social media integration',
          'Blog section setup',
          'Resume / CV download feature',
          'Testimonials section',
        ],
        deliverables: [
          'Complete portfolio website',
          'Content management guide',
          'SEO optimization report',
          'Performance audit',
        ],
      },
      {
        id: 'basic-static',
        title: 'Basic Static Website',
        category: 'static',
        unit: 'UNIT / S-03',
        ngn: '300,000',
        ngnRaw: 300000,
        usd: '200',
        usdRaw: 200,
        description: 'A bulletproof web presence for small businesses. Lightning-fast, secure, and zero backend complexity.',
        delivery: '10–12 DAYS',
        support: '60 DAYS',
        features: [
          'Up to 5 professionally designed pages',
          'Mobile-first responsive design',
          'Basic SEO with meta tags & sitemaps',
          'Contact form with email notifications',
          'Static hosting optimized (Vercel / Netlify)',
          'Core Web Vitals performance optimization',
          'SSL certificate and security headers',
          'Basic analytics integration',
        ],
        deliverables: [
          'Complete static website',
          'Hosting setup guide',
          'Maintenance documentation',
          'Performance report',
        ],
      },
    ],
  },
  {
    id: 'corporate',
    label: 'Corporate & CMS',
    rev: 'REV 2.0',
    tiers: [
      {
        id: 'corporate-portfolio',
        title: 'Corporate Portfolio',
        category: 'corporate',
        unit: 'UNIT / C-01',
        tag: 'POPULAR',
        ngn: '500,000',
        ngnRaw: 500000,
        usd: '333',
        usdRaw: 333,
        description: 'Enterprise-grade corporate presence engineered to build institutional trust, attract high-value clients, and command your market.',
        delivery: '12–15 DAYS',
        support: '90 DAYS',
        features: [
          'Up to 10 enterprise-grade pages',
          'Advanced SEO with keyword research & strategy',
          'Professional corporate branding package',
          'Detailed case studies with success metrics',
          'Team profiles & company history module',
          'Advanced analytics & conversion tracking',
          'Newsletter integration',
          'Multi-language support preparation',
          'Priority support & strategic consultation',
          'Custom contact forms with CRM integration',
        ],
        deliverables: [
          'Complete corporate website',
          'Brand guidelines document',
          'SEO strategy report',
          'Analytics setup & training',
          'Content management guide',
        ],
      },
      {
        id: 'blog-news',
        title: 'Blog / News Platform',
        category: 'corporate',
        unit: 'UNIT / C-02',
        ngn: '900,000',
        ngnRaw: 900000,
        usd: '600',
        usdRaw: 600,
        description: 'Dynamic content architecture for publishers, thought leaders, and content-driven brands. Built for scale and editorial velocity.',
        delivery: '15–20 DAYS',
        support: '120 DAYS',
        features: [
          'Unlimited pages with dynamic content management',
          'Advanced SEO with content optimization toolkit',
          'Custom design tailored to your editorial voice',
          'Full CMS integration (Sanity / Contentful)',
          'Newsletter integration with automation',
          'Comment system & social sharing',
          'RSS feeds & content syndication',
          'Author profiles & multi-author support',
          'Advanced search functionality',
          'Editorial workflow system',
        ],
        deliverables: [
          'Complete blog / news platform',
          'CMS training & documentation',
          'Content strategy guide',
          'SEO optimization toolkit',
          'Social media integration setup',
        ],
      },
      {
        id: 'corporate-cms',
        title: 'Corporate + CMS',
        category: 'corporate',
        unit: 'UNIT / C-03',
        ngn: '1,100,000',
        ngnRaw: 1100000,
        usd: '733',
        usdRaw: 733,
        description: 'Enterprise-level website with full content management capabilities. Scalable, secure, and built for organizational complexity.',
        delivery: '20–25 DAYS',
        support: '180 DAYS',
        features: [
          'Unlimited pages with scalable architecture',
          'Premium SEO with enterprise-grade tooling',
          'Fully custom design & user experience',
          'Advanced content management system',
          'Integrated blog with editorial workflow',
          'Multi-user roles & permissions',
          'Cloud hosting & automated backups',
          'Advanced security suite',
          'Performance monitoring dashboard',
          'API integration capabilities',
        ],
        deliverables: [
          'Enterprise-grade website',
          'Comprehensive CMS training',
          'Security audit report',
          'Performance optimization guide',
          'Technical documentation',
          'Backup & recovery procedures',
        ],
      },
    ],
  },
  {
    id: 'ecommerce',
    label: 'E-Commerce Solutions',
    rev: 'REV 3.0',
    tiers: [
      {
        id: 'basic-ecommerce',
        title: 'Basic E-Commerce',
        category: 'ecommerce',
        unit: 'UNIT / E-01',
        ngn: '900,000',
        ngnRaw: 900000,
        usd: '600',
        usdRaw: 600,
        description: 'Get to market fast. Essential e-commerce infrastructure with secure payment rails and a mobile-first shopping experience.',
        delivery: '18–22 DAYS',
        support: '120 DAYS',
        features: [
          'Up to 20 products with detailed listings',
          'E-commerce SEO optimization',
          'Complete shopping cart functionality',
          'Payment gateway integration (Paystack / Stripe)',
          'Mobile-optimized shopping experience',
          'Basic shipping & tax calculations',
          'Sales analytics & reporting dashboard',
          'Customer account system',
          'Order management panel',
          'Email notification system',
        ],
        deliverables: [
          'Complete e-commerce website',
          'Payment gateway setup',
          'Product management guide',
          'Order fulfillment documentation',
          'Basic marketing tools setup',
        ],
      },
      {
        id: 'standard-ecommerce',
        title: 'Standard E-Commerce',
        category: 'ecommerce',
        unit: 'UNIT / E-02',
        ngn: '1,500,000',
        ngnRaw: 1500000,
        usd: '1,000',
        usdRaw: 1000,
        description: 'A full-featured commerce engine. Advanced selling capabilities, intelligent inventory management, and conversion-optimized UX.',
        delivery: '25–30 DAYS',
        support: '180 DAYS',
        features: [
          'Up to 100 products with full category system',
          'Advanced SEO for product visibility',
          'Multiple payment gateway integration',
          'Inventory management system',
          'Customer accounts & full order history',
          'Discount codes & promotion engine',
          'Advanced shipping option matrix',
          'Email marketing integration',
          'Product reviews & ratings system',
          'Wishlist & comparison functionality',
          'Advanced analytics dashboard',
        ],
        deliverables: [
          'Advanced e-commerce platform',
          'Inventory management training',
          'Marketing automation setup',
          'Advanced analytics configuration',
          'Customer service tools',
          'Growth strategy consultation',
        ],
      },
      {
        id: 'premium-ecommerce',
        title: 'Premium E-Commerce',
        category: 'ecommerce',
        unit: 'UNIT / E-03',
        tag: 'ENTERPRISE',
        ngn: '2,500,000',
        ngnRaw: 2500000,
        usd: '1,667',
        usdRaw: 1667,
        description: 'Enterprise-grade commerce intelligence. Unlimited scale, AI-powered optimization, multi-currency support, and 365-day dedicated coverage.',
        delivery: '30–40 DAYS',
        support: '365 DAYS',
        features: [
          'Unlimited products & category architecture',
          'Premium SEO with AI-powered optimization',
          'Custom e-commerce feature development',
          'Multi-currency & language support',
          'CRM integration & marketing automation',
          'Advanced analytics & business intelligence',
          'Enterprise security & compliance suite',
          'Custom API development',
          'Advanced marketing automation',
          'Multi-vendor marketplace capability',
          'Priority 24/7 dedicated support',
        ],
        deliverables: [
          'Enterprise e-commerce solution',
          'Custom feature development',
          'Business intelligence dashboard',
          'Advanced security audit',
          'Performance optimization package',
          'Dedicated account management',
          'Ongoing strategic consultation',
        ],
      },
    ],
  },
  {
    id: 'webapps',
    label: 'Web Applications',
    rev: 'REV 4.0',
    tiers: [
      {
        id: 'admin-dashboard',
        title: 'Custom Dashboard',
        category: 'webapps',
        unit: 'UNIT / W-01',
        ngn: '800,000',
        ngnRaw: 800000,
        usd: '533',
        usdRaw: 533,
        description: 'Internal admin panels, analytics dashboards, and operational tools built for teams. Real-time data, intuitive UX, and role-based access control.',
        delivery: '15–20 DAYS',
        support: '90 DAYS',
        features: [
          'Custom admin panel with intuitive interface',
          'Real-time data visualization (charts, graphs, tables)',
          'Role-based access control (RBAC)',
          'REST API or GraphQL integration',
          'Authentication (JWT / OAuth / SSO)',
          'Export functionality (CSV, PDF, Excel)',
          'Activity logs and full audit trail',
          'Mobile-responsive layout',
          'Search, filter, and pagination systems',
          'Notification system (in-app & email)',
        ],
        deliverables: [
          'Fully functional dashboard application',
          'API integration documentation',
          'Admin user guide',
          'Deployment & hosting setup',
        ],
      },
      {
        id: 'saas-mvp',
        title: 'SaaS MVP',
        category: 'webapps',
        unit: 'UNIT / W-02',
        tag: 'POPULAR',
        ngn: '2,200,000',
        ngnRaw: 2200000,
        usd: '1,467',
        usdRaw: 1467,
        description: 'From concept to production-ready SaaS in 30 days. Full-stack architecture, subscription billing, multi-tenant support, and an onboarding flow that converts.',
        delivery: '25–35 DAYS',
        support: '180 DAYS',
        features: [
          'Multi-tenant SaaS architecture',
          'User authentication & account management',
          'Subscription billing (Stripe / Paystack)',
          'Usage-based feature gating',
          'Admin super-dashboard',
          'User onboarding flow & welcome sequence',
          'Email notifications & transactional emails',
          'Analytics & user activity tracking',
          'API-first design with documentation',
          'Scalable database architecture (PostgreSQL)',
          'CI/CD pipeline setup',
        ],
        deliverables: [
          'Production-ready SaaS application',
          'Billing & subscription system',
          'Admin dashboard',
          'Technical architecture documentation',
          'Deployment & DevOps setup',
          'Growth strategy consultation',
        ],
      },
      {
        id: 'fullstack-app',
        title: 'Full-Stack Web App',
        category: 'webapps',
        unit: 'UNIT / W-03',
        tag: 'ENTERPRISE',
        ngn: '4,500,000',
        ngnRaw: 4500000,
        usd: '3,000',
        usdRaw: 3000,
        description: 'Enterprise-grade web applications with complex business logic, deep integrations, and infrastructure designed to scale to millions of users.',
        delivery: '40–60 DAYS',
        support: '365 DAYS',
        features: [
          'Complex business logic & workflow automation',
          'Microservices or monolithic architecture (scoped)',
          'Third-party API & webhook integrations',
          'Real-time features (WebSockets / SSE)',
          'Advanced search & filtering (Elasticsearch)',
          'File upload / media management system',
          'Background job queue systems',
          'Comprehensive testing suite (unit + integration)',
          'Performance optimization & caching strategy',
          'Security hardening & penetration testing',
          'Load balancing & horizontal scaling setup',
          'Priority 24/7 dedicated support',
        ],
        deliverables: [
          'Production-grade web application',
          'Complete API documentation (Swagger)',
          'Architecture & database schema docs',
          'DevOps & infrastructure playbook',
          'Security audit report',
          'Performance benchmark report',
          'Dedicated account management',
        ],
      },
    ],
  },
  {
    id: 'maintenance',
    label: 'Maintenance & Retainers',
    rev: 'REV 5.0',
    tiers: [
      {
        id: 'basic-retainer',
        title: 'Care Plan — Basic',
        category: 'maintenance',
        unit: 'UNIT / M-01',
        ngn: '50,000',
        ngnRaw: 50000,
        usd: '33',
        usdRaw: 33,
        priceSuffix: '/mo',
        description: 'Monthly maintenance covering security updates, performance monitoring, and content changes. Peace of mind for business owners.',
        delivery: 'MONTHLY',
        support: 'ONGOING',
        features: [
          'Monthly security patches & updates',
          'Performance monitoring & Core Web Vitals checks',
          'Up to 2 hours of content updates per month',
          'Uptime monitoring (99.9% SLA)',
          'Monthly analytics & performance report',
          'Backup verification',
          '72-hour response time for requests',
        ],
        deliverables: [
          'Monthly maintenance report',
          'Uptime & performance summary',
          'Action log of all changes',
        ],
      },
      {
        id: 'pro-retainer',
        title: 'Care Plan — Pro',
        category: 'maintenance',
        unit: 'UNIT / M-02',
        ngn: '150,000',
        ngnRaw: 150000,
        usd: '100',
        usdRaw: 100,
        priceSuffix: '/mo',
        description: 'Comprehensive monthly retainer for businesses that need regular development work, priority support, and strategic growth guidance.',
        delivery: 'MONTHLY',
        support: 'ONGOING',
        features: [
          'Everything in Basic Care Plan',
          'Up to 8 hours of development work per month',
          'Priority 24-hour response time',
          'New feature development & improvements',
          'A/B testing & conversion optimization',
          'SEO monitoring & optimization',
          'Monthly strategy consultation (1hr call)',
          'Quarterly design refresh',
        ],
        deliverables: [
          'Monthly development summary',
          'Analytics & SEO report',
          'Strategy consultation notes',
          'Roadmap updates',
        ],
      },
      {
        id: 'enterprise-retainer',
        title: 'Enterprise Retainer',
        category: 'maintenance',
        unit: 'UNIT / M-03',
        ngn: '400,000',
        ngnRaw: 400000,
        usd: '267',
        usdRaw: 267,
        priceSuffix: '/mo',
        description: 'A fully embedded development partner. Dedicated hours, same-day response, and strategic oversight of your entire digital footprint.',
        delivery: 'MONTHLY',
        support: 'ONGOING',
        features: [
          'Everything in Pro Care Plan',
          'Up to 20 hours of development work per month',
          'Same-day emergency response (< 4 hrs)',
          'Dedicated Slack / WhatsApp channel',
          'Unlimited small content & copy updates',
          'Full-stack development on demand',
          'Weekly check-in calls',
          'Annual digital strategy review',
          'Priority access to new service launches',
        ],
        deliverables: [
          'Weekly progress updates',
          'Monthly executive summary',
          'Annual digital strategy document',
          'Dedicated project management dashboard',
        ],
      },
    ],
  },
];

export const allTiers: ServiceTier[] = categories.flatMap((c) => c.tiers);
